### ISSUE TITLE
Number of iterations in PBKDF2

### ISSUE THREAD

**Issue by kolleroot** [m9aertner/PBKDF2#5]
Hi Matthias,
I found quite a few options but I was unable to find an option to change the number of iterations in the PBKDF2 function. Is there an easy way to change it or do I have to change the source and rebuild the jar?

Thanks,
Stefan

**Comment by kolleroot** [comment]
I'm so sorry for this silly question. It doesn't make any sense to specify the number of iterations because the hashes aren't generated, only checked

**Comment by m9aertner** [comment]
Not a silly question at all!

Indeed, when the hashes are checked, the iteration count is read from the ascii-armoured result.
Example: `48290A0B96C426C3:1000:973899B1D4AFEB3ED371060D0797E0EE0142BD04` contains the iteration count as `:1000:`. Changing the count makes the verification fail, of course.

Just to be clear, the code can do _creation_, too, and with arbitrary iteration count! The `PBKDF2Parameters` class has the `iterationCount` as a property. So, to use the Jar in your code with a different iteration count, just set it there. No re-compilation needed.

Now, the iteration count is in fact _not exposed_ in the sample main function in `PBKDF2Engine`. In that sample program, it is fixed to 1000. It would be easy to add a command line parameter for the count, and when I get around to adding that I'll push it here.

Such parameter might also serve a purpose for _verification_ where it could denote a _minimal_ expected iteration count that cannot be undercut without failing the verification, i.e. as security parameter verification.

**Comment by kolleroot** [comment]
Thanks for the detailed response. Thats a quite nice idea to specify a minimal expected iteration count.

PS: It seems to work with Wildfly 10 too.
