### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by patrickfav** [m9aertner/PBKDF2#6]
What is the license with which the code is provided? I recommend adding the license indication to the README.md and add a LICENSE file in the root.

**Comment by m9aertner** [comment]
Hello Patrick,

the license is LGPL 2.1+. I hope that's OK for you.

The actual source code carries respective notes in header comments and on the (old) web page I have mentioned the license, too, with Link (see http://rtner.de/software/PBKDF2.html).

    This code may be used freely under the terms of the LGPL.

I shall amend the repsitory as per your suggestion nevertheless, thanks for the pointer and suggestion!

**Comment by patrickfav** [comment]
Hi m9aertner,

Sorry, I've missed the link. Thanks for the quick reply (and the great lib)

Btw. an advantage of having the LICENSE file in the root is that it will appear in the top right bar in your github project like so: https://github.com/google/gson
