### ISSUE TITLE
Checking password is not constant time algorithm

### ISSUE THREAD

**Issue by jarirajari** [m9aertner/PBKDF2#7]
Verifying password is susceptible to timing attacks, and should be handled with constant time algorithm.

**Comment by m9aertner** [comment]
Thanks for reviewing the code! I am aware of the concept of "constant time algorithm" and that attack vectors open up themselves when this is not honoured appropriately.

I trust you refer to the non-constant-time comparison in the `verifyKey` function?
```java
        for (int i = 0; i < inputKey.length; i++)
        {
            if (inputKey[i] != referenceKey[i])
            {
                return false;
            }
        }
```
I agree that a **best practice** would be to turn this into a constant-time iterated OR of the XOR, maybe along the following lines:
```java
        int z = 0;
        for (int i = 0; i < inputKey.length; i++)
        {
            z |= (inputKey[i] ^ referenceKey[i]);
        }
        return (z == 0);
```
It would certainly be interesting to first use a timing attack with a _known password_ to figure out the assumed unknown iteration count, then in a second phase attack the unknown _target password_. If you actually tried out such attack for real against such a piece of Java/JVM code please do let me know!

**Comment by jarirajari** [comment]
You are welcome! And thank you for doing the actual heavy work by implementing the algorithm! Nice work, and I am the user of the library.

Yes, I am referring to `verifyKey` method. My first thoughts to fix the method were:

1. Don't do early optimizations like string length checks
2. Use `for` loop to count _differences_ between input string and secret string. Of course, if the calculated difference is non-zero the passwords do not match
3. Use _input_ string as the basis for comparison so that the calculation time is _always_ based on it

Dislaimer: I am not familiar with byte-code level optimizations so it might be that there is still room for improvements, and it might even be possible that there is logical error in this proposal.

**Comment by m9aertner** [comment]
Amended in v1.1.4
